---
sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - vendor/bin/phpunit
...